# Generated by Django 4.1.7 on 2023-03-16 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objetivosApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objetivo',
            old_name='usuario',
            new_name='user',
        ),
    ]
